### ISSUE TITLE
Still getting the ENOENT error

### ISSUE THREAD

**Issue by FrikkieSnyman** [bojidaryovchev/next-amplify#1]
Hey @bojidaryovchev!

Appreciate that you've made this repo and for your feedback here: https://github.com/prisma/prisma/issues/10200

I'm pretty sure I have the exact same setup that you have in this repo (minus the graphql stuff)

Just wondering if you are reliably able to deploy a nextjs + prisma app to Amplify?

Let me know if I can share some more details about my setup to see if you are able to help? Maybe we can even jump on a call?

**Comment by bojidaryovchev** [comment]
hey there, could u please describe your issue more thoroughly? I cannot understand your problem from what you've written here.. keep in mind I have deleted my aws resources regarding this repo, so now it exists purely as code here

**Comment by FrikkieSnyman** [comment]
Ah sure thing!

As mentioned, I've got the same set-up that you have in this repo. Here is my `package.json`:

```
{
...
"dependencies": {
    "@next-auth/prisma-adapter": "^1.0.1",
    "@prisma/client": "3.9.2",
    "aws-sdk": "^2.1073.0",
    "dotenv": "^15.0.0",
    "next": "12.0.9",
    "next-auth": "^4.1.2",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "swr": "^1.2.1",
  },
  "devDependencies": {
    "@types/node": "17.0.13",
    "@types/react": "17.0.38",
    "prisma": "^3.9.2",
    "typescript": "4.5.5"
  }
}
```

My `next.config.js`:

```
require("dotenv").config();
/** @type {import('next').NextConfig} */
module.exports = {
  reactStrictMode: true,
  target: "experimental-serverless-trace",
  images: {
    domains: ["redacted.s3.amazonaws.com"],
  },
  webpack: (config, { isServer }) => {
    if (isServer) {
      config.externals.push("_http_common");
    }
    // Important: return the modified config
    return config;
  },
};
```

and finally, my `schema.prisma`:
```
generator client {
  provider        = "prisma-client-js"
  binaryTargets   = ["native", "rhel-openssl-1.0.x"]
  previewFeatures = ["extendedIndexes"]
}

datasource db {
  provider          = "postgresql"
  url               = env("DATABASE_URL")
  shadowDatabaseUrl = env("SHADOW_DATABASE_URL")
}
```

Deploying to AWS Amplify works fine - as in, it builds and deploys without error and I can reach my landing page. However, as soon as I navigate to the login page (which in my case, is the first step that you can go to that makes use of prisma), I get a 503 error response.

Looking at the logs of my edge lambda, I see the following:

```


@logStream | 2022/03/01/[1]db53c1d39d3a462fba5dc421ccc6e0e2
-- | --
@message | 2022-03-01T07:51:48.738Z be096882-fe31-4a23-9c93-7f433d3e8c90 ERROR Invoke Error {"errorType":"Error","errorMessage":"ENOENT: no such file or directory, open '/var/task/chunks/schema.prisma'","code":"ENOENT","errno":-2,"syscall":"open","path":"/var/task/chunks/schema.prisma","clientVersion":"3.9.2","stack":["Error: ENOENT: no such file or directory, open '/var/task/chunks/schema.prisma'"," at Object.openSync (fs.js:497:3)"," at Object.readFileSync (fs.js:393:35)"," at new LibraryEngine (/var/task/chunks/686.js:36281:40)"," at PrismaClient.getEngine (/var/task/chunks/686.js:40607:16)"," at new PrismaClient (/var/task/chunks/686.js:40578:29)"," at Module.58439 (/var/task/pages/api/auth/[...nextauth].js:263:16)"," at __webpack_require__ (/var/task/webpack-api-runtime.js:25:43)"," at Module.72484 (/var/task/pages/api/auth/[...nextauth].js:231:23)"," at __webpack_require__ (/var/task/webpack-api-runtime.js:25:43)"," at __webpack_exec__ (/var/task/pages/api/auth/[...nextauth].js:311:39)"]}
@requestId | be096882-fe31-4a23-9c93-7f433d3e8c90
@timestamp | 1646121108738
clientVersion | 3.9.2
code | ENOENT
errno | -2
errorMessage | ENOENT: no such file or directory, open '/var/task/chunks/schema.prisma'
errorType | Error
path | /var/task/chunks/schema.prisma
stack.0 | Error: ENOENT: no such file or directory, open '/var/task/chunks/schema.prisma'
stack.1 | at Object.openSync (fs.js:497:3)
stack.2 | at Object.readFileSync (fs.js:393:35)
stack.3 | at new LibraryEngine (/var/task/chunks/686.js:36281:40)
stack.4 | at PrismaClient.getEngine (/var/task/chunks/686.js:40607:16)
stack.5 | at new PrismaClient (/var/task/chunks/686.js:40578:29)
stack.6 | at Module.58439 (/var/task/pages/api/auth/[...nextauth].js:263:16)
stack.7 | at __webpack_require__ (/var/task/webpack-api-runtime.js:25:43)
stack.8 | at Module.72484 (/var/task/pages/api/auth/[...nextauth].js:231:23)
stack.9 | at __webpack_require__ (/var/task/webpack-api-runtime.js:25:43)
stack.10 | at __webpack_exec__ (/var/task/pages/api/auth/[...nextauth].js:311:39)
syscall | open
```

This is exactly the same issue that you had described here: https://github.com/prisma/prisma/issues/10200. Apparently, you got it solved by adding the `target` in your `next.config.js`.

So I was wondering if that fix was still working reliably for you, or if there were maybe any other steps that you might have taken that got it working?

Cheers

**Comment by bojidaryovchev** [comment]
you are using next@12 which is not supported by amplify, hence the 503 error, and the target property is no longer used in v12

here are the steps to take in order to create and deploy a v11 app (since it is currently a bit tricky)

1. npx create-next-app@latest --ts
2. amplify init
3. npm i -D -E chokidar
4. npm i -D -E eslint-config-next@11
5. npm i next@11
6. commit and push

please try those steps with a newly created app, and let me know if it works, it worked for me, however I was getting an error ```ERR! @next/swc-darwin-arm64 not accessible from next``` because apparently sometimes it fucks up the package-lock.json and forgets these entries
![image](https://user-images.githubusercontent.com/8954749/156539039-673ba5cf-78c4-48b9-8e60-04907d5de292.png)

**Comment by FrikkieSnyman** [comment]
Interesting. As I mentioned, it looks like Amplify is doing a fine job when deploying Next (even v12), but the problem comes in with Prisma.

 I'm not getting any success with any version of Next + Prisma any Amplify. 

Guess I'll look for a different hosting solution then!

Anyway, thanks for the help!

**Comment by bojidaryovchev** [comment]
its not the Prisma, its the API routes, try a simple API route like for the example the hello world, I am pretty sure it wouldnt work

**Comment by amitleuva1987** [comment]
@FrikkieSnyman , you just need to add below line under inputs:  section in your serverless.yml  

`useServerlessTraceTarget: true`

I just resolve it today with next 12.1.9. Here is my [issue url](https://github.com/serverless-nextjs/serverless-next.js/issues/2459)
